### ISSUE TITLE
Post fader FX: on my case isn't working

### ISSUE THREAD

**Issue by tormyvancool** [AudioIdeas/AudioIdeas-Projects#1]
Hi

I immediately installed the post fader FX as you know from FB and YT channel :-)
of course Im' unlucky .. in my case it doesn't work

please here the animated GIF.
Perhaps it's something I'm doing wrong but I mimic your video to be sure and .. well isn't working as it should

please here the link to the GIF [LINK](https://i.imgur.com/tRtbWLj.gif)

**Comment by tormyvancool** [comment]
Please I add here the Project file. Reaper 7.15 64 bit.

- Start Script: post-fader-insert.lua
- Insert the Fiedler Composer
- Insert the Fiedler Beam
- Insert the JS: Audioideas Projects/post-fader-insert/post-fader-fx-end.jsfx and the JS: Audioideas Projects/post-fader-insert/post-fader-fx-start.jsfx as FX
- Shift teh Beam between the 2 ones
- Add the noise generator before any plugin (it is the very first)

I don't get the "mechanism" working
[Dolby Atmos Post Fader FX.zip](https://github.com/AudioIdeas/AudioIdeas-Projects/files/15204121/Dolby.Atmos.Post.Fader.FX.zip)

**Comment by AudioIdeas** [comment]
Seems like the script is not running. Can you verify that the volume parameter in the plugins is moving while you move the fader? When I loaded your project and started the script then everything worked as expected.

<img width="658" alt="Screenshot 2024-05-04 at 10 22 50" src="https://github.com/AudioIdeas/AudioIdeas-Projects/assets/145033457/41521ccc-47ca-4a7e-91e3-3bd66d330293">

**Comment by tormyvancool** [comment]
> Seems like the script is not running. Can you verify that the volume parameter in the plugins is moving while you move the fader? When I loaded your project and started the script then everything worked as expected.
> 
>

Ah yes I verified it yesterday night after have re-watched several time syour 2 videos ... no one of the plugins' cursors are moving. nor the start nor the end.

Note: I always run the initial script.  Difficult to say if that script is really in runtime or is crashing off. So what I did is to re-click on the script and this window popped up
![image](https://github.com/AudioIdeas/AudioIdeas-Projects/assets/32305535/07384bcd-8a5a-4307-985d-a36332150b15)

It means that it was running

please here the UNLISTED video that shows up what I'm doing and how

[VIDEO](https://youtu.be/zXFCJrPYueU)

**Comment by AudioIdeas** [comment]
I have only tested the script on Mac. I'll fire up Windows version and see if there's something going on there.

**Comment by tormyvancool** [comment]
> I have only tested the script on Mac. I'll fire up Windows version and see if there's something going on there.

Just noticing that into the API reaper.TrackFX_GetFXName there are 3 parameters instead of the 2 forecast by the documentation.
Can this have some kind of influence?
![image](https://github.com/AudioIdeas/AudioIdeas-Projects/assets/32305535/5a9c1b79-a104-4f51-b332-042eaaaf0e46)

**Comment by AudioIdeas** [comment]
There's something strange going on in your setup. I did following, can you try this also:
- Install Reaper and Reapack in Windows 11 machine
- Import repository
- Install scripts and plugins that have name "post-fader" (3 plugins, 1 script)
- Run post-fader script
- Create new track
- Insert post-fader start on track and open the plugin GUI
- Move the channel fader
-> the volume parameter in the plugin should move

![image](https://github.com/AudioIdeas/AudioIdeas-Projects/assets/145033457/ad932a38-644e-453b-bb85-a2650cf2a374)

**Comment by AudioIdeas** [comment]
Although this is a long shot, can you try to use Reaper default theme?

**Comment by tormyvancool** [comment]
> Although this is a long shot, can you try to use Reaper default theme?

My installation is on a W11 machine.
However now I installed a Portable version always on the same machine. I installed your scripts and they are working perfectly
I also tried to install SWS: your scripts stil working

But on the normal installation: not at all

NOTE: I always used the default theme. I just modified a ibt the contrast in mine one that's it.

**Comment by tormyvancool** [comment]
In the normal installation, I had a global startup action defined in SWS which is the Solger's ReaLanucher.
I tired to get rid of and restarted Reaper: your scripts still not working as they should.

While with the portable version: they do work.

There is nothing else active in the Normal installation (Production)

**Comment by AudioIdeas** [comment]
That's strange. I also installed it normally, so it was not portable, and there was no problem whatsoever. I can review the code still, but it's bit difficult to fix stuff when I cannot replicate the bug. However, I'll leave this issue open since something is clearly wrong.

**Comment by tormyvancool** [comment]
> That's strange. I also installed it normally, so it was not portable, and there was no problem whatsoever. I can review the code still, but it's bit difficult to fix stuff when I cannot replicate the bug. However, I'll leave this issue open since something is clearly wrong.

is there anything to be setup in preferences, so far?

**Comment by AudioIdeas** [comment]
There should be nothing since I did a clean install on a machine that never had Reaper installed. Can you export your configuration and send it to me? Like this:
https://www.reapertips.com/post/how-to-export-import-reaper-settings

**Comment by tormyvancool** [comment]
> There should be nothing since I did a clean install on a machine that never had Reaper installed. Can you export your configuration and send it to me? Like this: https://www.reapertips.com/post/how-to-export-import-reaper-settings

Yes I know how to export it https://youtube.com/shorts/YBYDF875uPQ fortunately I make tutorials :-D :-D 

Do you need something specific from the configuration? Or everything?

**Comment by AudioIdeas** [comment]
The purpose wasn't to undermine knowledge :)
Yes, everything would be good

**Comment by tormyvancool** [comment]
> The purpose wasn't to undermine knowledge :) Yes, everything would be good

Please here the [link](https://drive.google.com/file/d/1Jv3HuG70NexDsue9hWsXRD-qnvZeZxZF/view?usp=sharing). Please inform me when you downloaded it so I put it as private.

**Comment by AudioIdeas** [comment]
Got it! And I'm on it I think!

**Comment by tormyvancool** [comment]
> Got it! And I'm on it I think!

So, I ran the portable version with the REAPER.ini of the Production version, that I renamed REAPER_Studio.ini ad pasted into the portable versions' folder and ran Reaper by using
`REAPER.exe -cfgfile REAPER_Studio.ini`

Your scripts are not working
Instead by using the default REAPER.ini they are working fine.

**Comment by AudioIdeas** [comment]
Update the script to 1.13 and see if it helps!

**Comment by tormyvancool** [comment]
> Update the script to 1.13 and see if it helps!

Super it work! What was the blocking stuff?

EDIT: tested also with nosi generator and Fiedler Beam and Fiedler Composer: everything is now fine.

**Comment by AudioIdeas** [comment]
Well, learned something today. It was the plugin name. I was looking for the plugins with "reaper.TrackFX_GetFXName" but it seems that this is looking for exactly what you have in your plugin browser. So, in your config it shows the path and file while in default config is shows the name. I probably should use some GUID thing for search, but nevertheless, now it works. Thanks for providing with all the info!

**Comment by tormyvancool** [comment]
> Well, learned something today. It was the plugin name. I was looking for the plugins with "reaper.TrackFX_GetFXName" but it seems that this is looking for exactly what you have in your plugin browser. So, in your config it shows the path and file while in default config is shows the name. I probably should use some GUID thing for search, but nevertheless, now it works. Thanks for providing with all the info!

Thanks to you for the brilliant solution.
You can close the issue :-)
